# matugen kitty colors
cursor            #84d6c2
cursor_text_color #00382e

foreground            #dee4e0
background            #090f0e
selection_foreground  #1d352f
selection_background  #b1ccc4
url_color             #b1ccc4

#: black 000000 767676
color0  #0e1513
color8  #303634
#: red cc0403 f2201f
color1  #011915
color9  #06ad93
#: green 19cb00 23fd00
color2  #b1ccc4
color10 #cde8e0
#: yellow cecb00 fffd00
color3  #aacbe4
color11 #c8e6ff
#: blue 0d73cc 1a8fff
color4  #005144
color12 #84d6c2
#: magenta cb1ed1 fd28ff
color5  #334b45
color13 #b1ccc4
#: cyan 0dcdcd 14ffff
color6  #2a4a5f
color14 #aacbe4
#: white dddddd ffffff
color7  #bfc9c4
color15 #dee4e0

mark1_foreground #00201a
mark1_background #a0f2de
mark2_foreground #06201a
mark2_background #cde8e0
mark3_foreground #001e2e
mark3_background #c8e6ff

active_tab_foreground #00382e
active_tab_background #84d6c2
inactive_tab_foreground #a0f2de
inactive_tab_background #005144

active_border_color #84d6c2
inactive_border_color #00382e
