#    __ ___ __  __
#   / //_(_) /_/ /___ __
#  / ,< / / __/ __/ // /
# /_/|_/_/\__/\__/\_, /
#                /___/
#
# Configuration
font_family                 JetBrainsMono Nerd Font
font_size                   13
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
remember_window_size        no
initial_window_width        950
initial_window_height       500
cursor_blink_interval       0.5
cursor_stop_blinking_after  1
scrollback_lines            2000
wheel_scroll_min_lines      1
enable_audio_bell           no
window_padding_width        20
hide_window_decorations     yes
background_opacity          1
dynamic_background_opacity  no
confirm_os_window_close     0
show_scrollbar no
shell                       zsh
# Cursor customization
cursor_shape                beam
cursor_beam_thickness       1.5
cursor_blink_interval       0.5
cursor_stop_blinking_after  1.0
cursor_trail                3
cursor_trail_decay          0.1 0.5
cursor_trail_start_threshold 0

# Tab Bar design
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         round
tab_bar_margin_width        6.0
tab_bar_margin_height       6.0 6.0
active_tab_font_style       bold-italic
inactive_tab_font_style     normal

# Window layout & Borders
window_margin_width         6
single_window_margin_width  0
draw_minimal_borders        yes
# active_border_color         #b8bb26
# inactive_border_color       #3c3836

# URL styles
detect_urls                 yes
# url_color                   #fe8019
url_style                   curly

# --- Theme Palette (Gruvbox Dark Fallback) ---
# Main colors
# foreground                  #ebdbb2
# background                  #282828
# selection_foreground        #665c54
# selection_background        #ebdbb2
# cursor                      #a89984
# cursor_text_color           #282828

# Tab bar colors
# active_tab_foreground       #282828
# active_tab_background       #fabd2f
# inactive_tab_foreground     #a89984
# inactive_tab_background     #3c3836
# tab_bar_background          #1d2021

# The 16 terminal colors
# Black
# color0 #282828
# color8 #928374
# Red
# color1 #cc241d
# color9 #fb4934
# Green
# color2 #98971a
# color10 #b8bb26
# Yellow
# color3 #d79921
# color11 #fabd2f
# Blue
# color4 #458588
# color12 #83a598
# Magenta
# color5 #b16286
# color13 #d3869b
# Cyan
# color6 #689d6a
# color14 #8ec07c
# White
# color7 #a89984
# color15 #ebdbb2

# Include wallpaper colors if available
include ./colors-matugen.conf
include ~/.cache/wallust/colors-kitty.conf

# Include Custom Configuration
# Create the file custom.conf in ~/.config/kitty to overwrite the default configuration
# include ./custom.conf

# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME